### ISSUE TITLE
Total number of at risk interactions?

### ISSUE THREAD

**Issue by Yvo-Hunink-The-Hague** [minvws/nl-covid19-notification-app-statistics#5]
I was looking to request some additional info here. Not sure if it is the right place to do so.

I am interested in knowing the total amount of risky interactions that were published, for an analysis I am doing of the effectiveness of the app. 

Am I correct that this is impossible, since there are fake interactions being published to hide some transactions that might expose individuals if people know they only interacted with 1 person?

Is there any other data that might help my analysis some more?

Again if this is the wrong place, I am sorry!

### Governance
- [X ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by ijansch** [comment]
Hi Yvo,

The answer depends on what you mean by 'interactions'.:

* risky meetings between persons) are never published, in fact, they are not sent to a server at all. All interactions stay local on the phone, so it is not technically possible to count the number of this type of interactions.
* If you mean the amount of uploads: a user only uploads their set of keys (up to 14 days of keys). Whether those keys have 'met' other people is not known, only that the keys belong to a person that was tested positively.

There are 2 type of 'fake interactions' (we call them decoys):

1) The app will sometimes randomly upload fake keys. This is to prevent that someone's network traffic could reveal that they are infected. 
2) If there are less than 150 keys to publish in a single batch, keys are added to ensure a minimum of 150. This prevents that someone could know which keys belong together. (e.g. if there are only 14 keys in the batch, you could derive that that's from 1 or 2 persons and link the keys together). This however only happens if it's less than 150. If there are for example 1000 keys in the batch, all of them are real.

Note that you can't derive the number of uploads from the number of keys, since a user can upload 0 keys or multiple keys (up to 14 days worth of keys). We do however publish the number of actual uploads in this repository. The amount of. uploads is always the real number, we only 'stuff' the key sets, but not the number of uploads.

**Comment by ijansch** [comment]
I'll close the issue, feel free to re-open if the above wasn't yet satisfactory, happy to elaborate.

**Comment by Yvo-Hunink-The-Hague** [comment]
Sure, issue can be closed!

The reason I was asking was this draft article<https://medium.com/@yvohunink/how-effective-has-the-corona-app-been-in-the-netherlands-f4218953301> I have been setting up, evaluating the effectivity of the app until now.

Since you guys are open about everything, I wish to be open to you to! Maybe you have some tips and considerations to improve the article?

--
Yvo Hunink
Concernadviseur Innovatie
Gemeente Den Haag
Dienst Bedrijfsvoering
Directie Informatie en ICT
Activiteiten
Conscious Cities                               (video<https://www.youtube.com/watch?v=LtbIgVIMhjc>)                  Smart The Hague
Slimme Energie                                 (video<https://www.youtube.com/watch?v=EPK7sZRWKnc&feature=youtu.be>)                  Living Lab Scheveningen
Privacy by Design x SSI                    (Website<https://www.koios.online/ssi>)             The Hague University of Applied Sciences - Blockchain Minor (Website<https://www.koios.online/ssi>)

+31 6 50 05 12 69
yvo.hunink@denhaag.nl<mailto:yvo.hunink@denhaag.nl>
www.denhaag.nl<http://www.denhaag.nl>
